 name: WuufusWaypoints
 author: Wuufu
 main: com.github.jarada.waypoints.PluginMain
 version: ${project.version}
 prefix: WuufusWaypoints
 api-version: 1.13
 commands:
   wp:
     description: Waypoints top-level command
     usage: /wp <add | move | remove | rename | select | desc | icon | discover | toggle | reload>
   sethome:
     description: Save up to three locations as waypoints
     usage: /sethome <name>
   setspawn:
     description: Sets spawn point for current world
     usage: /setspawn
 permissions:
   wp.*:
     description: Grants all plugin permissions except instant teleportation
     children:
       wp.admin: true
       wp.player: true
       wp.reload: true
       wp.access.*: true
       wp.beacon.*: true
       wp.respawn: true
     default: op
   wp.admin:
     description: Grants access to all commands except reload, allows player to select server-defined waypoints
     children:
       wp.bypass: true
       wp.add: true
       wp.desc: true
       wp.hint: true
       wp.icon: true
       wp.move: true
       wp.remove: true
       wp.rename: true
       wp.select.*: true
       wp.sethome: true
       wp.setspawn: true
       wp.toggle: true
   wp.access.*:
     description: Grants access to all waypoints
     children:
       wp.access.bed: true
       wp.access.spawn: true
   wp.add:
     description: Grants ability to add server-defined waypoints
   wp.beacon.*:
     description: Grants all beacon permissions
     children:
       wp.beacon.use: true
       wp.beacon.server: true
       wp.beacon.unlimited: true
   wp.bypass:
     description: Grants ability to teleport to disabled waypoints
   wp.desc:
     description: Grants ability to set a selected waypoint's description using commands
   wp.hint:
     description: Grants ability to set a selected waypoint's hint used when showing waypoints in discovery mode using commands
   wp.icon:
     description: Grants ability to set a selected waypoint's icon using commands
   wp.instant:
     description: Grants instant teleportation
   wp.move:
     description: Grants ability to move a selected waypoint using commands
   wp.player:
     description: Grants access to create manage home waypoints through world interaction
   wp.reload:
     description: Grants access to reload the plugin
   wp.remove:
     description: Grants ability to remove a selected waypoint using commands
   wp.rename:
     description: Grants ability to rename a selected waypoint icon using commands
   wp.respawn:
     description: Grants players the ability to use Waypoint Beacons to set their respawn point to home waypoints
   wp.select.*:
     description: Grants access to select using both methods
     children:
       wp.select.beacon: true
       wp.select.command: true
   wp.sethome:
     description: Grants players the ability to create home waypoints using commands
   wp.setspawn:
     description: Grants players ability to set their spawn point using commands
   wp.toggle:
     description: Grants ability to enable or disable a selected waypoint using commands
